### ISSUE TITLE
(IMPORT FAILED) ComfyUI-ELLA-wrapper 

### ISSUE THREAD

**Issue by AdvertiserM** [kijai/ComfyUI-IC-Light#17]
I tried installing through manager in comfy, then i tried installing manually, I tried running pip install -r requirements.txt in different folders but still no luck. What could I be doing incorrectly here? 
![image](https://github.com/kijai/ComfyUI-IC-Light/assets/13671218/b7947646-df2b-4e4e-9de3-9d50ac4e1838)

**Comment by kijai** [comment]
I think you posted this on the wrong repository? The conflict message can be ignored, it's just that both packs have same node. For import errors in general, there should be a more verbose error in the start up log stating what module exactly fails to import.

**Comment by AdvertiserM** [comment]
![image](https://github.com/kijai/ComfyUI-IC-Light/assets/13671218/71e63fee-abe6-4d0a-894b-79831d8f2e74)
Sorry about that, but here it is. 
Error handling request
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
                                       ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'class_type'
got prompt
[ERROR] An error occurred during the on_prompt_handler processing
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 650, in trigger_on_prompt
    json_data = handler(json_data)
                ^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 885, in prompt_handler
    if node["class_type"] == "smZ CLIPTextEncode":
       ~~~~^^^^^^^^^^^^^^
KeyError: 'class_type'

Error handling request
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 54, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
                                       ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'class_type'

**Comment by kijai** [comment]
> ![image](https://private-user-images.githubusercontent.com/13671218/330649617-71e63fee-abe6-4d0a-894b-79831d8f2e74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzA2ODYsIm5iZiI6MTcxNTc3MDM4NiwicGF0aCI6Ii8xMzY3MTIxOC8zMzA2NDk2MTctNzFlNjNmZWUtYWJlNi00ZDBhLTg5NGItNzk4MzFkOGYyZTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDEwNTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYzcxZWIwN2E5ODBiMWQ1YTA3YTIyNjg5ODY4OTUyYjljMjhmMzI0MzM4NmM3ZjhhMTVhZjdlY2Y4Y2E4ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rGjqjsVfUAwg1R7JwHZkmWxuJ5MtcH2kp3-7EKuRlA4) Sorry about that, but here it is. Error handling request Traceback (most recent call last): File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request resp = await request_handler(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle resp = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 42, in cache_control response: web.Response = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 54, in cors_middleware response = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 469, in post_prompt valid = execution.validate_prompt(prompt) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 625, in validate_prompt class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']] ~~~~~~~~~^^^^^^^^^^^^^^ KeyError: 'class_type' got prompt [ERROR] An error occurred during the on_prompt_handler processing Traceback (most recent call last): File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 650, in trigger_on_prompt json_data = handler(json_data) ^^^^^^^^^^^^^^^^^^ File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 885, in prompt_handler if node["class_type"] == "smZ CLIPTextEncode": ~~~~^^^^^^^^^^^^^^ KeyError: 'class_type'
> 
> Error handling request Traceback (most recent call last): File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request resp = await request_handler(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle resp = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl return await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 42, in cache_control response: web.Response = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 54, in cors_middleware response = await handler(request) ^^^^^^^^^^^^^^^^^^^^^^ File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 469, in post_prompt valid = execution.validate_prompt(prompt) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 625, in validate_prompt class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']] ~~~~~~~~~^^^^^^^^^^^^^^ KeyError: 'class_type'

That node in the screenshot from "Fihade" is not my node, just am unsupported copy, it should not be used.
