### ISSUE TITLE
"Load and Apply IC-Light" is err.:" IC-Light: Could not patch calculate_weight" ,please help

### ISSUE THREAD

**Issue by maxstewm** [kijai/ComfyUI-IC-Light#53]
!!! Exception during processing !!! IC-Light: Could not patch calculate_weight
Traceback (most recent call last):
  File "F:\maxste\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light\nodes.py", line 81, in load
    lora.calculate_weight = calculate_weight_adjust_channel_new(lora.calculate_weight)
                                                                ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.lora' has no attribute 'calculate_weight'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\maxste\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 313, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\maxste\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 188, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\maxste\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 165, in map_node_over_list
    process_inputs(input_dict, i)
  File "F:\maxste\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\maxste\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light\nodes.py", line 83, in load
    raise Exception("IC-Light: Could not patch calculate_weight")
Exception: IC-Light: Could not patch calculate_weight

Prompt executed in 7.19 seconds
got prompt
Failed to validate prompt for output 34:
* VAEDecode 33:
  - Required input is missing: samples
Output will be ignored
LoadAndApplyICLightUnet: Checking IC-Light Unet path
LoadAndApplyICLightUnet: Loading IC-Light Unet weights
LoadAndApplyICLightUnet: Attempting to add patches with IC-Light Unet weights
LoadAndApplyICLightUnet: Added LoadICLightUnet patches
!!! Exception during processing !!! IC-Light: Could not patch calculate_weight
Traceback (most recent call last):
  File "F:\maxste\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light\nodes.py", line 81, in load
    lora.calculate_weight = calculate_weight_adjust_channel_new(lora.calculate_weight)
                                                                ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.lora' has no attribute 'calculate_weight'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\maxste\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 313, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\maxste\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 188, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\maxste\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 165, in map_node_over_list
    process_inputs(input_dict, i)
  File "F:\maxste\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\maxste\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light\nodes.py", line 83, in load
    raise Exception("IC-Light: Could not patch calculate_weight")
Exception: IC-Light: Could not patch calculate_weight

Prompt executed in 3.84 seconds
got prompt
Failed to validate prompt for output 34:
* VAEDecode 33:
-------------------------------------------------------------------------------

I can't find the reason, need help

Python 3.12.4

**Comment by kijai** [comment]
Update ComfyUI.

**Comment by Milor123** [comment]
@kijai Same problem after update your nodes, but it solved after of update ComfyUI, thanks  ❤️

**Comment by maxstewm** [comment]
thanks @kijai , it solved  after i update "update_comfyui_and_python_dependencies".
and i Downgrade numpy to 1.26.4

**Comment by anubhabPanda** [comment]
@kijai Having the same issue as above even after updating comfyui. Any resolutions?

**Comment by kijai** [comment]
> @kijai Having the same issue as above even after updating comfyui. Any resolutions?

I don't know, just make absolutely sure it's actually updated. I just updated ComfyUI to latest and everything works fine with it, so nothing new has broken.

**Comment by anubhabPanda** [comment]
> > @kijai Having the same issue as above even after updating comfyui. Any resolutions?
> 
> I don't know, just make absolutely sure it's actually updated. I just updated ComfyUI to latest and everything works fine with it, so nothing new has broken.

It is fixed now. ComfyUi was not getting updated from the model manager. Had to manually update it from the repo. Thanks

**Comment by biubiubiyabiu** [comment]
Error occurred when executing LoadAndApplyICLightUnet:

IC-Light: Could not patch calculate_weight - IC-Light: The 'calculate_weight' function does not exist in 'lora'

File "F:\AI\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\AI\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\AI\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\AI\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light\nodes.py", line 78, in load
raise Exception(f"IC-Light: Could not patch calculate_weight - {str(e)}")

**Comment by abumolly** [comment]
> Error occurred when executing LoadAndApplyICLightUnet:
> 
> IC-Light: Could not patch calculate_weight - IC-Light: The 'calculate_weight' function does not exist in 'lora'
> 
> File "F:\AI\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\AI\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\AI\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\AI\ComfyUI_windows_portable_nvidia (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light\nodes.py", line 78, in load raise Exception(f"IC-Light: Could not patch calculate_weight - {str(e)}")

me too and have you solved the problem?

**Comment by abumolly** [comment]
Error occurred when executing LoadAndApplyICLightUnet:

IC-Light: Could not patch calculate_weight - IC-Light: The 'calculate_weight' function does not exist in 'lora'

File "/Users/yingying/ComfyUI/execution.py", line 313, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/yingying/ComfyUI/execution.py", line 188, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/yingying/ComfyUI/execution.py", line 165, in map_node_over_list
process_inputs(input_dict, i)
File "/Users/yingying/ComfyUI/execution.py", line 154, in process_inputs
results.append(getattr(obj, func)(**inputs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/yingying/ComfyUI/custom_nodes/ComfyUI-IC-Light/nodes.py", line 78, in load
raise Exception(f"IC-Light: Could not patch calculate_weight - {str(e)}")
------------------------------------------anyone can help?

**Comment by kijai** [comment]
> IC-Light: Could not patch calculate_weight - IC-Light: The 'calculate_weight' function does not exist in 'lora'

This means your ComfyUI itself needs to be updated. I just tested and these nodes currently work fine with latest ComfyUI version.

**Comment by abumolly** [comment]
> > IC-Light: Could not patch calculate_weight - IC-Light: The 'calculate_weight' function does not exist in 'lora'
> 
> This means your ComfyUI itself needs to be updated. I just tested and these nodes currently work fine with latest ComfyUI version.

----------------------------------------------------------------------------------------------------------------------
Thank you and after I updated comfyUI, the error updated as below :
Requested to load AutoencoderKL
Loading 1 new model
loaded completely 0.0 319.11416244506836 True
Requested to load BaseModel
Loading 1 new model
WARNING SHAPE MISMATCH diffusion_model.input_blocks.0.0.weight WEIGHT NOT MERGED torch.Size([320, 8, 3, 3]) != torch.Size([320, 4, 3, 3])
IC-Light: Merged with diffusion_model.input_blocks.0.0.weight channel changed from torch.Size([320, 4, 3, 3]) to [320, 8, 3, 3]
loaded completely 0.0 1639.406135559082 True
100%|██████████████████████████████████████████████████████████| 19/19 [00:40<00:00,  2.12s/it]
Unloading models for lowram load.
0 models unloaded.
/Users/yingying/ComfyUI/nodes.py:1503: RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))

![Uploading 截屏2024-09-27 10.12.48.png…]()
